# Assembles the all-in-one FleetShift image from published component images.
# Used by the openshift/release periodic that publishes quay.io/stolostron/fleetshift.
FROM quay.io/stolostron/fleetshift-server:latest
COPY --from=quay.io/stolostron/fleetshift-web:latest /srv/web /srv/web
CMD ["serve", "--http-addr", ":8085", "--grpc-addr", ":50051", "--db", "/data/fleetshift.db", "--web-dir", "/srv/web", "--log-level", "debug"]
