import fs from "fs";
import { createRequire } from "module";
import path from "path";

/**
 * Returns MF shared-module entries for each dynamic entry point
 * generated by `@fleetshift/common`'s build step.
 *
 * Mirrors {@link getDynamicModules} for PatternFly — each source
 * file in common gets its own shared-module key so plugins only
 * bundle the common modules they actually import.
 */
export default function getCommonDynamicModules(): Record<
  string,
  { requiredVersion: string; version: string }
> {
  const req = createRequire(import.meta.url);
  const commonPkgDir = path.dirname(
    req.resolve("@fleetshift/common/package.json"),
  );
  const mapPath = path.resolve(commonPkgDir, "dist/common-modules.json");

  if (!fs.existsSync(mapPath)) {
    console.warn(
      "[@fleetshift/build-utils] common-modules.json not found — run common:build first",
    );
    return {};
  }

  const moduleMap: Record<string, string> = JSON.parse(
    fs.readFileSync(mapPath, "utf-8"),
  );

  // Deduplicate: multiple exports can map to the same dynamic path
  const uniquePaths = new Set(Object.values(moduleMap));

  const modules: Record<string, { requiredVersion: string; version: string }> =
    {};
  for (const dynamicPath of uniquePaths) {
    const key = `@fleetshift/common/${dynamicPath}`;
    modules[key] = { requiredVersion: "*", version: "0.0.0" };
  }

  return modules;
}
