services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev --import-realm
    restart: unless-stopped
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD
      - KC_HTTP_ENABLED=false
      - KC_HTTPS_PORT=${KC_HTTPS_PORT}
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/keycloak.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/keycloak.key
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME=https://${KC_HOSTNAME}:${KC_HTTPS_PORT}/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HEALTH_ENABLED=true
    ports:
      - "${KC_HTTPS_PORT}:${KC_HTTPS_PORT}"
    volumes:
      - ./.certs/keycloak.crt:/opt/keycloak/certs/keycloak.crt:ro,z
      - ./.certs/keycloak.key:/opt/keycloak/certs/keycloak.key:ro,z
      - ./.realm.json:/opt/keycloak/data/import/fleetshift-realm.json:ro,z
    networks:
      - default
      - kind
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

  fleetshift-server:
    command:
      - serve
      - ${DB_FLAG}
      - --http-addr=:${FLEETSHIFT_SERVER_HTTP_PORT}
      - --grpc-addr=:${FLEETSHIFT_SERVER_GRPC_PORT}
      - --log-level=${FLEETSHIFT_LOG_LEVEL}
      - --addons=${FLEETSHIFT_SERVER_ADDONS:-kind,kubernetes}
      - --web-dir=${FLEETSHIFT_WEB_DIR:-/srv/web}
      - --oidc-ca-file=/certs/ca.crt
      - --oidc-issuer=https://${KC_HOSTNAME}:${KC_HTTPS_PORT}/auth/realms/fleetshift
      - --oidc-ui-client-id=${OIDC_UI_CLIENT_ID:-fleetshift-ui}
      - --oidc-ui-scope=${OIDC_UI_SCOPE:-openid profile email groups audience:server:client_id:fleetshift}
      - --oidc-resource-audience=${OIDC_RESOURCE_AUDIENCE:-fleetshift}
      - --oidc-key-enrollment-audience=${OIDC_KEY_ENROLLMENT_AUDIENCE:-fleetshift-signing}
      - --oidc-public-key-claim-expression=${PUBLIC_KEY_CLAIM_EXPR:-}
      - --oidc-registry-id=${KEY_REGISTRY_ID:-}
      - --oidc-registry-subject-expression=${KEY_REGISTRY_SUBJECT_EXPR:-}
    volumes:
      - ./.certs/ca.crt:/certs/ca.crt:ro,z
