package aioinit

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"text/template"

	"golang.org/x/crypto/bcrypt"
)

const (
	// dexConfigDir holds Dex config + sqlite (mode 0700, dex UID/GID).
	dexConfigDir = "/data/sandbox/dex"
	// dexConfigPath is the Dex config file (mode 0600, dex UID/GID).
	dexConfigPath = "/data/sandbox/dex/config.yaml"
	// dexDBPath is the sealed Dex SQLite store.
	dexDBPath = "/data/sandbox/dex/dex.db"

	bcryptCost = 12

	opsPassword = "fleetshift-ops"
	devPassword = "fleetshift-dev"
)

// DexRenderInput is the peer-Dex issuer and public endpoint metadata needed to
// write Dex config (Dex-on only). Dex listens on container-loopback HTTP;
// TLS is terminated at the AIO edge.
type DexRenderInput struct {
	Issuer    string
	Endpoints Endpoints
}

// DexPaths holds Dex config and SQLite install locations.
type DexPaths struct {
	ConfigDir  string
	ConfigPath string
	DBPath     string
}

// DefaultDexPaths returns the fixed Dex store/config layout under /data/sandbox/dex.
func DefaultDexPaths() DexPaths {
	return DexPaths{ConfigDir: dexConfigDir, ConfigPath: dexConfigPath, DBPath: dexDBPath}
}

// InstallDexConfig bcrypt-hashes demo passwords, generates a resource-client
// secret, and atomically installs the Dex config with required ownership.
func InstallDexConfig(in DexRenderInput, paths DexPaths, dexUID, dexGID int) error {
	opsHash, err := bcrypt.GenerateFromPassword([]byte(opsPassword), bcryptCost)
	if err != nil {
		return fmt.Errorf("hash ops password: %w", err)
	}
	devHash, err := bcrypt.GenerateFromPassword([]byte(devPassword), bcryptCost)
	if err != nil {
		return fmt.Errorf("hash dev password: %w", err)
	}
	secret, err := randomResourceClientSecret(32)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(paths.ConfigDir, 0700); err != nil {
		return fmt.Errorf("dex config dir: %w", err)
	}
	if os.Geteuid() == 0 {
		// Dex must create sqlite under this directory; own it as dex:dex.
		if err := os.Chown(paths.ConfigDir, dexUID, dexGID); err != nil {
			return fmt.Errorf("chown dex config dir: %w", err)
		}
	}
	if err := os.Chmod(paths.ConfigDir, 0700); err != nil {
		return err
	}

	data := dexTemplateData{
		Issuer:         in.Issuer,
		Listen:         in.Endpoints.DexListen,
		UICallback:     in.Endpoints.UICallback,
		SilentRenew:    in.Endpoints.SilentRenew,
		DBPath:         paths.DBPath,
		OpsHash:        string(opsHash),
		DevHash:        string(devHash),
		ResourceSecret: secret,
	}
	tmp := paths.ConfigPath + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	if err := dexTemplate.Execute(f, data); err != nil {
		_ = f.Close()
		_ = os.Remove(tmp)
		return fmt.Errorf("render dex config: %w", err)
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if os.Geteuid() == 0 {
		if err := os.Chown(tmp, dexUID, dexGID); err != nil {
			_ = os.Remove(tmp)
			return fmt.Errorf("chown dex config: %w", err)
		}
	}
	if err := os.Chmod(tmp, 0600); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, paths.ConfigPath)
}

// dexTemplateData is the Dex YAML template binding.
type dexTemplateData struct {
	Issuer         string
	Listen         string
	UICallback     string
	SilentRenew    string
	DBPath         string
	OpsHash        string
	DevHash        string
	ResourceSecret string
}

// randomResourceClientSecret returns a URL-safe random string of n random bytes.
func randomResourceClientSecret(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("resource client secret: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

var dexTemplate = template.Must(template.New("dex").Parse(`# Generated by fleetshift aio-init. Do not edit.
issuer: {{.Issuer}}
storage:
  type: sqlite3
  config:
    file: {{.DBPath}}
web:
  http: {{.Listen}}
oauth2:
  skipApprovalScreen: true
  passwordConnector: local
enablePasswordDB: true
staticPasswords:
  - email: "ops@fleetshift.local"
    hash: "{{.OpsHash}}"
    username: "ops-user"
    userID: "fleetshift-sandbox-ops-v1"
    name: "FleetShift Operator"
    preferredUsername: "ops-user"
    groups:
      - "ops"
  - email: "dev@fleetshift.local"
    hash: "{{.DevHash}}"
    username: "dev-user"
    userID: "fleetshift-sandbox-dev-v1"
    name: "FleetShift Developer"
    preferredUsername: "dev-user"
    groups:
      - "dev"
staticClients:
  - id: fleetshift
    name: FleetShift Resource Server
    secret: {{.ResourceSecret}}
    public: false
    trustedPeers:
      - fleetshift-ui
      - fleetshift-cli
  - id: fleetshift-ui
    name: FleetShift UI
    public: true
    redirectURIs:
      - {{.UICallback}}
      - {{.SilentRenew}}
  - id: fleetshift-cli
    name: FleetShift CLI
    public: true
  - id: fleetshift-signing
    name: FleetShift Signing Enrollment
    public: true
`))
